--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/OutiServer/PMMPScheduleMessage
build-by-default: true
branches:
- main
projects:
  PMMPScheduleMessage:
    path: ""
    libs:
      - src: ifera-mc/ConfigUpdater/ConfigUpdater
        version: ^2.0.0
...
