name: ScheduleMessage
description: Plugin to periodically post specified messages
author: Ken_Cir
version: 1.0.0
api: 4.0.0
main: outiserver\schedulemessage\ScheduleMessage
src-namespace-prefix: outiserver\schedulemessage